version: '3.8'

volumes:
  postgres-data:

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: rep-vegas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rep-vegas-db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
